#!/bin/bash

set -e

if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
then
   echo 1>&2
   echo "Could not find mysql database.  Please run:" 1>&2
   echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.1" 1>&2
   echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
   echo 1>&2
fi

if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
then 
   exit 5
fi
